services:
  database:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    env_file:
      - .env
      - .env.dev
      - .env.staging
    volumes:
      - ./db:/var/lib/postgresql/database
